services:
  - type: web
    name: video
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm run start
    plan: free
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: GEMINI_API_KEY
        sync: false
      - key: EACHLABS_API_KEY
        sync: false
      - key: keyID
        sync: false
      - key: keyName
        sync: false
      - key: applicationKey
        sync: false

staticSites:
  - name: huemo-frontend
    rootDir: frontend
    buildCommand: ""
    publishPath: .
    headers:
      - path: "/*"
        name: "Cache-Control"
        value: "public, max-age=3600"

